// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLOB_CHROMATIN_WIRE_H_
#define FLATBUFFERS_GENERATED_BLOB_CHROMATIN_WIRE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace chromatin {
namespace wire {

struct Blob;
struct BlobBuilder;
struct BlobT;

struct BlobT : public ::flatbuffers::NativeTable {
  typedef Blob TableType;
  std::vector<uint8_t> namespace_id{};
  std::vector<uint8_t> pubkey{};
  std::vector<uint8_t> data{};
  uint32_t ttl = 0;
  uint64_t timestamp = 0;
  std::vector<uint8_t> signature{};
};

struct Blob FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlobT NativeTableType;
  typedef BlobBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAMESPACE_ID = 4,
    VT_PUBKEY = 6,
    VT_DATA = 8,
    VT_TTL = 10,
    VT_TIMESTAMP = 12,
    VT_SIGNATURE = 14
  };
  const ::flatbuffers::Vector<uint8_t> *namespace_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_NAMESPACE_ID);
  }
  const ::flatbuffers::Vector<uint8_t> *pubkey() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PUBKEY);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  uint32_t ttl() const {
    return GetField<uint32_t>(VT_TTL, 0);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *signature() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_SIGNATURE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAMESPACE_ID) &&
           verifier.VerifyVector(namespace_id()) &&
           VerifyOffset(verifier, VT_PUBKEY) &&
           verifier.VerifyVector(pubkey()) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyField<uint32_t>(verifier, VT_TTL, 4) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_SIGNATURE) &&
           verifier.VerifyVector(signature()) &&
           verifier.EndTable();
  }
  BlobT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(BlobT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Blob> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlobT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct BlobBuilder {
  typedef Blob Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_namespace_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> namespace_id) {
    fbb_.AddOffset(Blob::VT_NAMESPACE_ID, namespace_id);
  }
  void add_pubkey(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pubkey) {
    fbb_.AddOffset(Blob::VT_PUBKEY, pubkey);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(Blob::VT_DATA, data);
  }
  void add_ttl(uint32_t ttl) {
    fbb_.AddElement<uint32_t>(Blob::VT_TTL, ttl, 0);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(Blob::VT_TIMESTAMP, timestamp, 0);
  }
  void add_signature(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> signature) {
    fbb_.AddOffset(Blob::VT_SIGNATURE, signature);
  }
  explicit BlobBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Blob> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Blob>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Blob> CreateBlob(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> namespace_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pubkey = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0,
    uint32_t ttl = 0,
    uint64_t timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> signature = 0) {
  BlobBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_signature(signature);
  builder_.add_ttl(ttl);
  builder_.add_data(data);
  builder_.add_pubkey(pubkey);
  builder_.add_namespace_id(namespace_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Blob> CreateBlobDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *namespace_id = nullptr,
    const std::vector<uint8_t> *pubkey = nullptr,
    const std::vector<uint8_t> *data = nullptr,
    uint32_t ttl = 0,
    uint64_t timestamp = 0,
    const std::vector<uint8_t> *signature = nullptr) {
  auto namespace_id__ = namespace_id ? _fbb.CreateVector<uint8_t>(*namespace_id) : 0;
  auto pubkey__ = pubkey ? _fbb.CreateVector<uint8_t>(*pubkey) : 0;
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  auto signature__ = signature ? _fbb.CreateVector<uint8_t>(*signature) : 0;
  return chromatin::wire::CreateBlob(
      _fbb,
      namespace_id__,
      pubkey__,
      data__,
      ttl,
      timestamp,
      signature__);
}

::flatbuffers::Offset<Blob> CreateBlob(::flatbuffers::FlatBufferBuilder &_fbb, const BlobT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline BlobT *Blob::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<BlobT>(new BlobT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Blob::UnPackTo(BlobT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = namespace_id(); if (_e) { _o->namespace_id.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->namespace_id.begin()); } }
  { auto _e = pubkey(); if (_e) { _o->pubkey.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->pubkey.begin()); } }
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
  { auto _e = ttl(); _o->ttl = _e; }
  { auto _e = timestamp(); _o->timestamp = _e; }
  { auto _e = signature(); if (_e) { _o->signature.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->signature.begin()); } }
}

inline ::flatbuffers::Offset<Blob> Blob::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const BlobT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateBlob(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Blob> CreateBlob(::flatbuffers::FlatBufferBuilder &_fbb, const BlobT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const BlobT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _namespace_id = _o->namespace_id.size() ? _fbb.CreateVector(_o->namespace_id) : 0;
  auto _pubkey = _o->pubkey.size() ? _fbb.CreateVector(_o->pubkey) : 0;
  auto _data = _o->data.size() ? _fbb.CreateVector(_o->data) : 0;
  auto _ttl = _o->ttl;
  auto _timestamp = _o->timestamp;
  auto _signature = _o->signature.size() ? _fbb.CreateVector(_o->signature) : 0;
  return chromatin::wire::CreateBlob(
      _fbb,
      _namespace_id,
      _pubkey,
      _data,
      _ttl,
      _timestamp,
      _signature);
}

inline const chromatin::wire::Blob *GetBlob(const void *buf) {
  return ::flatbuffers::GetRoot<chromatin::wire::Blob>(buf);
}

inline const chromatin::wire::Blob *GetSizePrefixedBlob(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<chromatin::wire::Blob>(buf);
}

inline bool VerifyBlobBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<chromatin::wire::Blob>(nullptr);
}

inline bool VerifySizePrefixedBlobBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<chromatin::wire::Blob>(nullptr);
}

inline void FinishBlobBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<chromatin::wire::Blob> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBlobBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<chromatin::wire::Blob> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<chromatin::wire::BlobT> UnPackBlob(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<chromatin::wire::BlobT>(GetBlob(buf)->UnPack(res));
}

inline std::unique_ptr<chromatin::wire::BlobT> UnPackSizePrefixedBlob(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<chromatin::wire::BlobT>(GetSizePrefixedBlob(buf)->UnPack(res));
}

}  // namespace wire
}  // namespace chromatin

#endif  // FLATBUFFERS_GENERATED_BLOB_CHROMATIN_WIRE_H_
