// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRANSPORT_CHROMATINDB_WIRE_H_
#define FLATBUFFERS_GENERATED_TRANSPORT_CHROMATINDB_WIRE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace chromatindb {
namespace wire {

struct TransportMessage;
struct TransportMessageBuilder;
struct TransportMessageT;

enum TransportMsgType : int8_t {
  TransportMsgType_None = 0,
  TransportMsgType_KemPubkey = 1,
  TransportMsgType_KemCiphertext = 2,
  TransportMsgType_AuthSignature = 3,
  TransportMsgType_AuthPubkey = 4,
  TransportMsgType_Ping = 5,
  TransportMsgType_Pong = 6,
  TransportMsgType_Goodbye = 7,
  TransportMsgType_Data = 8,
  TransportMsgType_SyncRequest = 9,
  TransportMsgType_SyncAccept = 10,
  TransportMsgType_NamespaceList = 11,
  TransportMsgType_BlobRequest = 13,
  TransportMsgType_BlobTransfer = 14,
  TransportMsgType_SyncComplete = 15,
  TransportMsgType_PeerListRequest = 16,
  TransportMsgType_PeerListResponse = 17,
  TransportMsgType_Delete = 18,
  TransportMsgType_DeleteAck = 19,
  TransportMsgType_Subscribe = 20,
  TransportMsgType_Unsubscribe = 21,
  TransportMsgType_Notification = 22,
  TransportMsgType_StorageFull = 23,
  TransportMsgType_TrustedHello = 24,
  TransportMsgType_PQRequired = 25,
  TransportMsgType_QuotaExceeded = 26,
  TransportMsgType_ReconcileInit = 27,
  TransportMsgType_ReconcileRanges = 28,
  TransportMsgType_ReconcileItems = 29,
  TransportMsgType_SyncRejected = 30,
  TransportMsgType_WriteAck = 31,
  TransportMsgType_ReadRequest = 32,
  TransportMsgType_ReadResponse = 33,
  TransportMsgType_ListRequest = 34,
  TransportMsgType_ListResponse = 35,
  TransportMsgType_StatsRequest = 36,
  TransportMsgType_StatsResponse = 37,
  TransportMsgType_MIN = TransportMsgType_None,
  TransportMsgType_MAX = TransportMsgType_StatsResponse
};

inline const TransportMsgType (&EnumValuesTransportMsgType())[37] {
  static const TransportMsgType values[] = {
    TransportMsgType_None,
    TransportMsgType_KemPubkey,
    TransportMsgType_KemCiphertext,
    TransportMsgType_AuthSignature,
    TransportMsgType_AuthPubkey,
    TransportMsgType_Ping,
    TransportMsgType_Pong,
    TransportMsgType_Goodbye,
    TransportMsgType_Data,
    TransportMsgType_SyncRequest,
    TransportMsgType_SyncAccept,
    TransportMsgType_NamespaceList,
    TransportMsgType_BlobRequest,
    TransportMsgType_BlobTransfer,
    TransportMsgType_SyncComplete,
    TransportMsgType_PeerListRequest,
    TransportMsgType_PeerListResponse,
    TransportMsgType_Delete,
    TransportMsgType_DeleteAck,
    TransportMsgType_Subscribe,
    TransportMsgType_Unsubscribe,
    TransportMsgType_Notification,
    TransportMsgType_StorageFull,
    TransportMsgType_TrustedHello,
    TransportMsgType_PQRequired,
    TransportMsgType_QuotaExceeded,
    TransportMsgType_ReconcileInit,
    TransportMsgType_ReconcileRanges,
    TransportMsgType_ReconcileItems,
    TransportMsgType_SyncRejected,
    TransportMsgType_WriteAck,
    TransportMsgType_ReadRequest,
    TransportMsgType_ReadResponse,
    TransportMsgType_ListRequest,
    TransportMsgType_ListResponse,
    TransportMsgType_StatsRequest,
    TransportMsgType_StatsResponse
  };
  return values;
}

inline const char * const *EnumNamesTransportMsgType() {
  static const char * const names[39] = {
    "None",
    "KemPubkey",
    "KemCiphertext",
    "AuthSignature",
    "AuthPubkey",
    "Ping",
    "Pong",
    "Goodbye",
    "Data",
    "SyncRequest",
    "SyncAccept",
    "NamespaceList",
    "",
    "BlobRequest",
    "BlobTransfer",
    "SyncComplete",
    "PeerListRequest",
    "PeerListResponse",
    "Delete",
    "DeleteAck",
    "Subscribe",
    "Unsubscribe",
    "Notification",
    "StorageFull",
    "TrustedHello",
    "PQRequired",
    "QuotaExceeded",
    "ReconcileInit",
    "ReconcileRanges",
    "ReconcileItems",
    "SyncRejected",
    "WriteAck",
    "ReadRequest",
    "ReadResponse",
    "ListRequest",
    "ListResponse",
    "StatsRequest",
    "StatsResponse",
    nullptr
  };
  return names;
}

inline const char *EnumNameTransportMsgType(TransportMsgType e) {
  if (::flatbuffers::IsOutRange(e, TransportMsgType_None, TransportMsgType_StatsResponse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTransportMsgType()[index];
}

struct TransportMessageT : public ::flatbuffers::NativeTable {
  typedef TransportMessage TableType;
  chromatindb::wire::TransportMsgType type = chromatindb::wire::TransportMsgType_None;
  std::vector<uint8_t> payload{};
};

struct TransportMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransportMessageT NativeTableType;
  typedef TransportMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_PAYLOAD = 6
  };
  chromatindb::wire::TransportMsgType type() const {
    return static_cast<chromatindb::wire::TransportMsgType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::Vector<uint8_t> *payload() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PAYLOAD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           verifier.VerifyVector(payload()) &&
           verifier.EndTable();
  }
  TransportMessageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TransportMessageT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TransportMessage> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TransportMessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TransportMessageBuilder {
  typedef TransportMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(chromatindb::wire::TransportMsgType type) {
    fbb_.AddElement<int8_t>(TransportMessage::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_payload(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> payload) {
    fbb_.AddOffset(TransportMessage::VT_PAYLOAD, payload);
  }
  explicit TransportMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TransportMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TransportMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TransportMessage> CreateTransportMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    chromatindb::wire::TransportMsgType type = chromatindb::wire::TransportMsgType_None,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> payload = 0) {
  TransportMessageBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TransportMessage> CreateTransportMessageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    chromatindb::wire::TransportMsgType type = chromatindb::wire::TransportMsgType_None,
    const std::vector<uint8_t> *payload = nullptr) {
  auto payload__ = payload ? _fbb.CreateVector<uint8_t>(*payload) : 0;
  return chromatindb::wire::CreateTransportMessage(
      _fbb,
      type,
      payload__);
}

::flatbuffers::Offset<TransportMessage> CreateTransportMessage(::flatbuffers::FlatBufferBuilder &_fbb, const TransportMessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline TransportMessageT *TransportMessage::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TransportMessageT>(new TransportMessageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TransportMessage::UnPackTo(TransportMessageT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = payload(); if (_e) { _o->payload.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->payload.begin()); } }
}

inline ::flatbuffers::Offset<TransportMessage> TransportMessage::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TransportMessageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTransportMessage(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TransportMessage> CreateTransportMessage(::flatbuffers::FlatBufferBuilder &_fbb, const TransportMessageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TransportMessageT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _payload = _o->payload.size() ? _fbb.CreateVector(_o->payload) : 0;
  return chromatindb::wire::CreateTransportMessage(
      _fbb,
      _type,
      _payload);
}

inline const chromatindb::wire::TransportMessage *GetTransportMessage(const void *buf) {
  return ::flatbuffers::GetRoot<chromatindb::wire::TransportMessage>(buf);
}

inline const chromatindb::wire::TransportMessage *GetSizePrefixedTransportMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<chromatindb::wire::TransportMessage>(buf);
}

inline bool VerifyTransportMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<chromatindb::wire::TransportMessage>(nullptr);
}

inline bool VerifySizePrefixedTransportMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<chromatindb::wire::TransportMessage>(nullptr);
}

inline void FinishTransportMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<chromatindb::wire::TransportMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTransportMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<chromatindb::wire::TransportMessage> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<chromatindb::wire::TransportMessageT> UnPackTransportMessage(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<chromatindb::wire::TransportMessageT>(GetTransportMessage(buf)->UnPack(res));
}

inline std::unique_ptr<chromatindb::wire::TransportMessageT> UnPackSizePrefixedTransportMessage(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<chromatindb::wire::TransportMessageT>(GetSizePrefixedTransportMessage(buf)->UnPack(res));
}

}  // namespace wire
}  // namespace chromatindb

#endif  // FLATBUFFERS_GENERATED_TRANSPORT_CHROMATINDB_WIRE_H_
