"""chromatindb -- Python SDK for chromatindb PQ-secure decentralized database."""

__version__ = "0.1.0"

from chromatindb._directory import (
    Directory,
    DirectoryEntry,
    GroupEntry,
    decode_group_entry,
    decode_user_entry,
    encode_group_entry,
    encode_user_entry,
    make_delegation_data,
    verify_user_entry,
)
from chromatindb._envelope import envelope_decrypt, envelope_encrypt, envelope_parse
from chromatindb._hkdf import hkdf_derive, hkdf_expand, hkdf_extract
from chromatindb._reconnect import ConnectionState
from chromatindb.client import ChromatinClient
from chromatindb.types import (
    BatchReadResult,
    BlobRef,
    DelegationEntry,
    DelegationList,
    DeleteResult,
    ListPage,
    MetadataResult,
    NamespaceEntry,
    NamespaceListResult,
    NamespaceStats,
    NodeInfo,
    Notification,
    PeerDetail,
    PeerInfo,
    ReadResult,
    StorageStatus,
    TimeRangeEntry,
    TimeRangeResult,
    WriteResult,
)
from chromatindb.crypto import (
    AEAD_KEY_SIZE,
    AEAD_NONCE_SIZE,
    AEAD_TAG_SIZE,
    SHA3_256_SIZE,
    aead_decrypt,
    aead_encrypt,
    build_signing_input,
    sha3_256,
)
from chromatindb.exceptions import (
    ChromatinError,
    ConnectionError,
    CryptoError,
    DecodeError,
    DecryptionError,
    DirectoryError,
    HandshakeError,
    IdentityError,
    KeyDerivationError,
    KeyFileError,
    MalformedEnvelopeError,
    NamespaceError,
    NotARecipientError,
    ProtocolError,
    SignatureError,
    WireError,
)
from chromatindb.identity import Identity, KEM_PUBLIC_KEY_SIZE, KEM_SECRET_KEY_SIZE
from chromatindb.wire import (
    TransportMsgType,
    decode_transport_message,
    encode_transport_message,
)

__all__ = [
    "AEAD_KEY_SIZE",
    "AEAD_NONCE_SIZE",
    "AEAD_TAG_SIZE",
    "BatchReadResult",
    "BlobRef",
    "ChromatinClient",
    "ChromatinError",
    "ConnectionState",
    "ConnectionError",
    "CryptoError",
    "DecodeError",
    "DelegationEntry",
    "DelegationList",
    "DeleteResult",
    "DecryptionError",
    "Directory",
    "DirectoryEntry",
    "DirectoryError",
    "GroupEntry",
    "HandshakeError",
    "Identity",
    "IdentityError",
    "KEM_PUBLIC_KEY_SIZE",
    "KEM_SECRET_KEY_SIZE",
    "KeyDerivationError",
    "KeyFileError",
    "ListPage",
    "MalformedEnvelopeError",
    "MetadataResult",
    "NamespaceEntry",
    "NamespaceError",
    "NamespaceListResult",
    "NamespaceStats",
    "NodeInfo",
    "NotARecipientError",
    "Notification",
    "PeerDetail",
    "PeerInfo",
    "ProtocolError",
    "ReadResult",
    "SHA3_256_SIZE",
    "SignatureError",
    "StorageStatus",
    "TimeRangeEntry",
    "TimeRangeResult",
    "TransportMsgType",
    "WireError",
    "WriteResult",
    "__version__",
    "aead_decrypt",
    "aead_encrypt",
    "build_signing_input",
    "decode_group_entry",
    "decode_transport_message",
    "decode_user_entry",
    "encode_group_entry",
    "encode_transport_message",
    "encode_user_entry",
    "envelope_decrypt",
    "envelope_encrypt",
    "envelope_parse",
    "hkdf_derive",
    "hkdf_expand",
    "hkdf_extract",
    "make_delegation_data",
    "sha3_256",
    "verify_user_entry",
]
